name: chatapp
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.13.1
  firebase_auth: ^3.3.9
  cloud_firestore: ^3.1.10
  firebase_messaging: ^11.2.8
  flutter_bloc: ^8.0.1
  get: ^4.6.1
  http: ^0.13.4
  shared_preferences: ^2.0.13
  firebase_storage: ^10.2.9
  image_picker: ^0.8.4+11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
